/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionType = IDL.Variant({
  'mcq' : IDL.Null,
  'long' : IDL.Null,
  'short' : IDL.Null,
});
export const Answer = IDL.Record({
  'marks' : IDL.Nat,
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'questionType' : QuestionType,
});
export const Chapter = IDL.Record({
  'title' : IDL.Text,
  'chapterNumber' : IDL.Nat,
  'subjectName' : IDL.Text,
});
export const Subject = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAnswersByChapter' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(Answer)],
      ['query'],
    ),
  'getChaptersBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'searchAnswers' : IDL.Func([IDL.Text], [IDL.Vec(Answer)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionType = IDL.Variant({
    'mcq' : IDL.Null,
    'long' : IDL.Null,
    'short' : IDL.Null,
  });
  const Answer = IDL.Record({
    'marks' : IDL.Nat,
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'questionType' : QuestionType,
  });
  const Chapter = IDL.Record({
    'title' : IDL.Text,
    'chapterNumber' : IDL.Nat,
    'subjectName' : IDL.Text,
  });
  const Subject = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getAnswersByChapter' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Answer)],
        ['query'],
      ),
    'getChaptersBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Chapter)],
        ['query'],
      ),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'searchAnswers' : IDL.Func([IDL.Text], [IDL.Vec(Answer)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };