/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'marks' : bigint,
  'question' : string,
  'answer' : string,
  'questionType' : QuestionType,
}
export interface Chapter {
  'title' : string,
  'chapterNumber' : bigint,
  'subjectName' : string,
}
export type QuestionType = { 'mcq' : null } |
  { 'long' : null } |
  { 'short' : null };
export interface Subject {
  'icon' : string,
  'name' : string,
  'description' : string,
}
export interface _SERVICE {
  'getAnswersByChapter' : ActorMethod<[string, bigint], Array<Answer>>,
  'getChaptersBySubject' : ActorMethod<[string], Array<Chapter>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'searchAnswers' : ActorMethod<[string], Array<Answer>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];